version: "1"

services:
  backend_sp:
    container_name: yourMusic-Backend-sp
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    environment:
      - spotify_client_id=816f97452ed24d0b8c5a52ed6a2e89ab
      - spotify_client_secret=ef50183287e446f0a72ee68ad30954a7
      - spotify_redirect_uri=http://localhost:8010/api/v1/callback.php
      - homepage_url=http://localhost:5173/
    ports:
      - 8010:80

  # frontend_sp:
  #   container_name: yourMusic-Frontend-sp
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #     args:
  #       VITE_API_URL: https://spbackend.tensi.dev/api/v1
  #   volumes:
  #     - ./frontend:/app

  #   depends_on:
  #     - backend_sp
networks:
  default:
    external: true
    name: mynetwork
